---
- name: Ensure WireGuard installed on Debian/Ubuntu
  ansible.builtin.apt:
    name: wireguard
    state: present
    update_cache: true
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Backup resolv.conf
  ansible.builtin.copy:
    src: /etc/resolv.conf
    dest: /etc/resolv.conf.backup
    remote_src: true
    force: false
    mode: "0644"
    owner: root
    group: root
  when: warp_native_modify_resolv

- name: Set temporary resolv.conf
  ansible.builtin.copy:
    content: |
      {% for ns in warp_native_temp_nameservers %}nameserver {{ ns }}
      {% endfor %}
    dest: /etc/resolv.conf
    mode: "0644"
    owner: root
    group: root
  when: warp_native_modify_resolv
