---
- name: stop and disable warp
  ansible.builtin.systemd:
    name: "wg-quick@{{ warp_native_conf_name | splitext | first }}"
    state: stopped
    enabled: false
    masked: false
    daemon_reload: true
  failed_when: false

- name: remove config file
  ansible.builtin.file:
    path: "{{ warp_native_conf_dir }}/{{ warp_native_conf_name }}"
    state: absent

- name: ensure conf dir exists
  ansible.builtin.file:
    path: "{{ warp_native_conf_dir }}"
    state: directory
    mode: "0755"

- name: remove wgcf account
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/wgcf-account.toml"
    state: absent
  when: warp_native_purge_all

- name: remove wgcf profile
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/wgcf-profile.conf"
    state: absent
  when: warp_native_purge_all

- name: remove wgcf binary
  ansible.builtin.file:
    path: "{{ warp_native_wgcf_install_path }}"
    state: absent
  when: warp_native_purge_all

- name: delete interface if exists
  ansible.builtin.command: ip link del "{{ warp_native_conf_name | splitext | first }}"
  register: warp_native_delif
  changed_when: warp_native_delif.rc == 0
  failed_when: false

- name: restore resolv.conf from backup
  ansible.builtin.copy:
    src: /etc/resolv.conf.backup
    dest: /etc/resolv.conf
    remote_src: true
  when: warp_native_modify_resolv and warp_native_cleanup_dns_backup
  ignore_errors: true

- name: remove resolv.conf backup
  ansible.builtin.file:
    path: /etc/resolv.conf.backup
    state: absent
  when: warp_native_modify_resolv and warp_native_cleanup_dns_backup

- name: remove wireguard package on debian family
  ansible.builtin.apt:
    name: wireguard
    state: absent
    purge: true
    update_cache: false
  when: ansible_os_family == "Debian" and warp_native_remove_wireguard_pkg

- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: true
