---
- name: Get WG show
  ansible.builtin.command: wg show {{ warp_native_conf_name | splitext | first }}
  register: warp_native_wg_show
  changed_when: false
  failed_when: false
  until: >-
    warp_native_wg_show.stdout is search('latest handshake: .*second|latest handshake: .*minute')
  retries: "{{ warp_native_check_retries }}"
  delay: "{{ warp_native_check_delay }}"

- name: WARP trace via curl
  ansible.builtin.command:
    argv:
      - curl
      - -s
      - --interface
      - "{{ warp_native_conf_name | splitext | first }}"
      - https://www.cloudflare.com/cdn-cgi/trace
  register: warp_native_trace
  changed_when: false
  failed_when: false
