---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-debian12
    image: debian:12
    privileged: true
    pre_build_image: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
